### ISSUE TITLE
update with latest and greatest in managing references in Quarto?

### ISSUE THREAD

**Issue by ryoliver** [eds-221-programming-essentials/EDS-221-programming-essentials.github.io#38]
https://github.com/eds-221-programming-essentials/EDS-221-programming-essentials.github.io/blob/9c29a49ad3250ca51b7f475e331b70b34bac67ab/course-materials/interactive-sessions/interactive-session-5.qmd#L485

**Comment by ryoliver** [comment]
@FlukeAndFeather I think you just mentioned new Quarto tools for this?

**Comment by FlukeAndFeather** [comment]
I believe the tools are built into RStudio, so they work for both RMarkdown and Quarto documents. You can insert citations from Zotero (as described) or directly from a DOI. I like the latter because it removes an intermediate step if you haven't added the citation to Zotero yet.

**Comment by ryoliver** [comment]
thanks!
